# Generated by Django 5.1.4 on 2025-01-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_alter_article_category_alter_mailbatch_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='user_id',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userschedule',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
